name: Astronomer CI - Deploy code

on:
  workflow_dispatch:
    inputs:
      deploymentId:
        description: "Deployment ID"
        required: false
        type: string

  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment ID based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOYMENT_ID=${{ secrets.MAIN_DEPLOYMENT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEPLOYMENT_ID=${{ secrets.DEVELOP_DEPLOYMENT_ID }}" >> $GITHUB_ENV
          fi

      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash

      - name: Set API Token for Astro
        env:
          ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
        run: |
          echo "API token set"

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.6
        with:
          deployment-id: ${{ env.DEPLOYMENT_ID }}
