name: Astronomer CI - Deploy code

on:
  workflow_dispatch:
    inputs:
      deploymentId:
        description: "Deployment ID"
        required: false
        type: string

  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment ID based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOYMENT_ID=${{ secrets.MAIN_DEPLOYMENT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEPLOYMENT_ID=${{ secrets.DEVELOP_DEPLOYMENT_ID }}" >> $GITHUB_ENV
          fi

      - name: Override with Workflow Dispatch Input if Provided
        if: ${{ github.event.inputs.deploymentId != '' }}
        run: echo "DEPLOYMENT_ID=${{ github.event.inputs.deploymentId }}" >> $GITHUB_ENV

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.6
        with:
          deployment-id: ${{ env.DEPLOYMENT_ID }}
          # action: deploy
          # workspace: ${{ secrets.ASTRO_WORKSPACE }}
